apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-metallb
  namespace: metallb-system
spec:
  addresses:
  - 10.0.0.220-10.0.0.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - local-metallb